def generate_header(class_name: str) -> str:
    guard = class_name.upper() + "_H"
    return f"""// This file was automatically generated.
// Do not edit manually.
// Generated by QtFormGenerator
// =====================================

#ifndef {guard}_H__
#define {guard}_H__

#include <QWidget>

class QLabel;
class QLineEdit;
class QCheckBox;
class QComboBox;
class QRadioButton;
class QSpinBox;
class QDoubleSpinBox;
class QTextEdit;
class QVBoxLayout;
class QHBoxLayout;
class QGridLayout;
class QButtonGroup;

class {class_name} : public QWidget {{
    Q_OBJECT

public:
    explicit {class_name}(QWidget* parent = nullptr);
    ~{class_name}();

private:
    void setupUi();
}};

#endif // {guard}_H__
"""

def generate_source(class_name: str) -> str:
    return f"""// This file was automatically generated.
// Do not edit manually.
// Generated by QtFormGenerator
// =====================================

#include "include/form/{class_name}.h"
#include <QLabel>
#include <QLineEdit>
#include <QCheckBox>
#include <QComboBox>
#include <QRadioButton>
#include <QSpinBox>
#include <QDoubleSpinBox>
#include <QTextEdit>
#include <QVBoxLayout>
#include <QHBoxLayout>
#include <QGridLayout>
#include <QButtonGroup>

{class_name}::{class_name}(QWidget* parent)
    : QWidget(parent)
{{
    setupUi();
}}

{class_name}::~{class_name}() = default;

void {class_name}::setupUi()
{{
    // TODO: 自动插入控件构建和布局代码
}}
"""
